# Generated by Django 5.2.7 on 2025-12-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
