# Generated by Django 5.2.7 on 2025-12-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_is_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_updated',
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20),
        ),
    ]
