# Generated by Django 5.2.7 on 2025-12-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_item_is_updated_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
