# Generated by Django 5.2.7 on 2025-12-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_contact_email_item_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='contact_email',
            new_name='email',
        ),
    ]
