# Generated by Django 5.2.7 on 2025-12-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_question_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='emoji',
            field=models.CharField(default='🔹', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='emoji',
            field=models.CharField(default='❓', max_length=10),
        ),
    ]
