# Generated by Django 5.2.7 on 2025-12-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_questionnairequestion_questionnaireoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
