# Generated by Django 5.2.7 on 2025-12-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_questionnaire_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairequestion',
            name='emoji',
            field=models.CharField(default='❓', max_length=10),
        ),
    ]
